// Host-only material. None of this operational content is sent to Player or Display.
export const spellingBeeWords = [
  ["EMBARRASSMENT", "im-BARR-us-muhnt", "A feeling of self-consciousness, shame or awkwardness.", "My greatest embarrassment was confidently waving back at someone who was waving at the person behind me.", "Double R and double S.", "From French embarrasser, influenced by Spanish and Portuguese embaraçar."],
  ["DIARRHOEA", "dye-uh-REE-uh", "Frequent passing of loose or watery stools.", "The spelling bee became alarmingly urgent when the contestant asked to use diarrhoea in a sentence.", "Australian/British spelling; American English usually uses diarrhea.", "From Greek dia, ‘through’, and rhein, ‘to flow’. Delightfully literal."],
  ["QUESTIONNAIRE", "kwes-chuh-NAIR", "A written set of questions used to gather information.", "The questionnaire asked whether I enjoyed questionnaires, so I lied.", "One N before the A, then double N.", "From French questionnaire, built from question."],
  ["ACCOMMODATION", "uh-kom-uh-DAY-shun", "A place to live or stay; also an adjustment made to suit a need.", "The luxury accommodation featured one towel and a kettle with emotional problems.", "Double C and double M.", "From Latin accommodare, ‘to make fit or suitable’."],
  ["CONSCIENTIOUS", "kon-shee-EN-shus", "Careful to do things thoroughly and correctly.", "The conscientious contestant checked every letter, then misspelled their own name.", "Do not confuse it with conscious.", "From Latin conscientia, meaning inner knowledge or conscience."],
  ["MILLENNIUM", "mil-EN-ee-um", "A period of one thousand years.", "It took almost a millennium for everyone to agree where to order dinner from.", "Double L and double N.", "From Latin mille, ‘thousand’, and annus, ‘year’."],
  ["SUPERSEDE", "soo-puh-SEED", "To replace something older or less effective.", "The air fryer did not supersede the oven; it merely became its smug little colleague.", "The only common English word ending in -sede; not supercede.", "From Latin supersedere, literally ‘to sit above’."],
  ["PHARAOH", "FAIR-oh", "A ruler of ancient Egypt.", "The pharaoh demanded a pyramid, excellent Wi-Fi and absolutely no follow-up questions.", "The unusual vowel order catches people.", "From ancient Egyptian pr-ꜥ3, ‘great house’, via Greek and Latin."],
  ["ONOMATOPOEIA", "on-uh-mat-uh-PEE-uh", "The formation of a word from the sound it represents.", "Crash is onomatopoeia, especially when Dad loads the dishwasher.", "The word itself came through Greek.", "From Greek onoma, ‘name’, and poiein, ‘to make’."],
  ["RHYTHM", "RITH-um", "A repeated pattern of sound or movement.", "He had perfect rhythm until someone turned a camera toward him.", "Famously written without A, E, I, O or U.", "From Greek rhythmos, through Latin and French."],
  ["LIAISON", "lee-AY-zon", "Communication or cooperation between people or groups.", "She acted as liaison between the barbecue and the smoke alarm.", "French in origin; the internal vowel sequence is the trap.", "From French lier, ‘to bind’."],
  ["MANOEUVRE", "muh-NOO-vuh", "A movement requiring skill and care.", "Reversing out of the driveway became a seventeen-point manoeuvre.", "Australian/British spelling; American English uses maneuver.", "From French manœuvre, ultimately Latin manu operari, ‘work by hand’."],
  ["CAMOUFLAGE", "KAM-uh-flahzh", "A disguise that helps something blend into its surroundings.", "His camouflage was flawless except for the fluorescent party hat.", "Borrowed from French.", "From French camoufler, ‘to disguise’."],
  ["HARASS", "huh-RASS", "To subject someone to persistent pressure or unwanted behaviour.", "The magpies continued to harass the cyclist, who had clearly offended them personally.", "One R, double S.", "Borrowed from French; its deeper origin is uncertain."],
  ["MAINTENANCE", "MAYN-tuh-nuhns", "Work done to keep something in good condition.", "The coffee machine entered maintenance mode precisely when civilisation needed it most.", "It loses the second I from maintain.", "From Old French maintenir, ‘to hold or keep’."],
  ["SEPARATE", "SEP-uh-rayt", "To divide or keep apart.", "Please separate the adults from anyone who says they do not like dessert.", "There is a rat in sep-a-rat-e.", "From Latin separare, ‘to set apart’."],
  ["PRIVILEGE", "PRIV-uh-lij", "A special right, advantage or honour.", "It was a privilege to host, and an even greater privilege to control the mute button.", "No D before the G.", "From Latin privilegium, ‘a law concerning a private person’."],
  ["OCCASIONALLY", "uh-KAY-zhuh-nuh-lee", "From time to time; not regularly.", "I occasionally exercise, usually by reaching for the remote.", "Double C, one S, then double L.", "From Latin occasio, through French and English."],
].map(([word, pronunciation, definition, example, notes, origin]) => ({
  word,
  pronunciation,
  definition,
  example,
  notes,
  origin,
}));
