// Secret performance prompts are intentionally imported by the Host only.
export const charadesPrompts = [
  "WALKING A DOG THAT IS MUCH STRONGER THAN YOU",
  "TRYING TO OPEN A STUBBORN JAR",
  "BUILDING FLAT-PACK FURNITURE WITHOUT INSTRUCTIONS",
  "A PENGUIN LEARNING TO FLY",
  "TAKING A SELFIE WITH A KANGAROO",
  "GETTING CAUGHT IN A SUDDEN HAILSTORM",
  "A CHEF DISCOVERING THE SOUP IS FAR TOO SPICY",
  "PARALLEL PARKING WHILE EVERYONE WATCHES",
  "CHASING A HAT DOWN A WINDY STREET",
  "STEPPING ON A LEGO BRICK",
];
